name: bootcamp2020 

on:
  push:
    branches: [ master ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: installing Node
      uses: action/setup-node@v2-beta
      with:
        node-version: 12
    - name: installing surge
      run: npm intsall --global surge
      
      -name: Deploying using surge
       run: surge ./ bootcamp2020byhayat.surge.sh --token $ {{ secrete.SURGE_TOKEN}}
